export type AnnaRecipeType =
  | "compliment"
  | "breakfast"
  | "lunch"
  | "dinner"
  | "must_have"
  | "recipe_day"
  | "drinks";

export type AnnaRecipeMetadata = {
  type: AnnaRecipeType;
  id: number;
  displayName: string;
  technicalName: string;
  page: number;
  day: number;
  week?: string;
  section: string;
  timeOfDay?: string;
  kind?: "recipe" | "technical";
};

// Read-only Anna-side search/navigation metadata derived from Book display catalog.
export const ANNA_RECIPE_METADATA: readonly AnnaRecipeMetadata[] = [
  {
    type: "compliment",
    id: 1,
    displayName: "АНИНЫ БУСЫ",
    technicalName: "Ягодно-яблочный мармелад на агаре",
    page: 129,
    day: 1,
    week: "Неделя 1",
    section: "Комплименты",
  },
  {
    type: "compliment",
    id: 2,
    displayName: "УЛЫБКА ФАКИРА",
    technicalName: "Энергетические шарики с финиками, миндалем и какао",
    page: 135,
    day: 2,
    week: "Неделя 1",
    section: "Комплименты",
  },
  {
    type: "compliment",
    id: 3,
    displayName: "ПОДАРОК ПЕРСЕИ",
    technicalName: "Намазка из авокадо, лимона и зелени",
    page: 140,
    day: 3,
    week: "Неделя 1",
    section: "Комплименты",
  },
  {
    type: "compliment",
    id: 4,
    displayName: "КОРИЧНОЕ ЗОЛОТО",
    technicalName: "Печенье из овсяных хлопьев и семян",
    page: 145,
    day: 4,
    week: "Неделя 1",
    section: "Комплименты",
  },
  {
    type: "compliment",
    id: 5,
    displayName: "СОЛНЦЕ КЛОНДАЙКА",
    technicalName: "Золотое молоко в порошке (домашняя смесь)",
    page: 150,
    day: 5,
    week: "Неделя 1",
    section: "Комплименты",
  },
  {
    type: "compliment",
    id: 6,
    displayName: "БЕЛЫЙ СТИХ",
    technicalName: "Паста из белой фасоли с чесноком и лимоном",
    page: 418,
    day: 6,
    week: "Неделя 2",
    section: "Комплименты",
  },
  {
    type: "compliment",
    id: 7,
    displayName: "МЯГКИЙ ОРЕШЕК",
    technicalName: "Быстрый ореховый сыр с семенами, зеленью и лимоном",
    page: 423,
    day: 7,
    week: "Неделя 2",
    section: "Комплименты",
  },
  {
    type: "compliment",
    id: 8,
    displayName: "ПОЧТИ КЛАССИКА",
    technicalName: "Печенье с финиками, овсянкой и семенами",
    page: 427,
    day: 8,
    week: "Неделя 2",
    section: "Комплименты",
  },
  {
    type: "compliment",
    id: 9,
    displayName: "PICCANTE",
    technicalName: "Тыквенное имбирное печенье",
    page: 432,
    day: 9,
    week: "Неделя 2",
    section: "Комплименты",
  },
  {
    type: "compliment",
    id: 10,
    displayName: "КРАСНЫЙ БАРХАТ",
    technicalName: "Томатно-перечный соус",
    page: 694,
    day: 10,
    week: "Неделя 3 (соусы)",
    section: "Комплименты",
  },
  {
    type: "compliment",
    id: 11,
    displayName: "ФИОЛЕТОВОЕ ОБЛАКО",
    technicalName: "Баклажаново-имбирный крем",
    page: 696,
    day: 11,
    week: "Неделя 3 (соусы)",
    section: "Комплименты",
  },
  {
    type: "compliment",
    id: 12,
    displayName: "ЗОЛОТОЙ ПОТОК",
    technicalName: "Морковно-цитрусовый соус",
    page: 698,
    day: 12,
    week: "Неделя 3 (соусы)",
    section: "Комплименты",
  },
  {
    type: "compliment",
    id: 13,
    displayName: "ОГНЕННЫЙ ПОЦЕЛУЙ",
    technicalName: "Острый перечный соус",
    page: 700,
    day: 13,
    week: "Неделя 3 (соусы)",
    section: "Комплименты",
  },
  {
    type: "compliment",
    id: 14,
    displayName: "ЗЕЛЁНЫЙ ШЁПОТ",
    technicalName: "Соус из брокколи и зелени",
    page: 702,
    day: 14,
    week: "Неделя 3 (соусы)",
    section: "Комплименты",
  },
  {
    type: "compliment",
    id: 15,
    displayName: "СЛИВОЧНАЯ ТЫКВА",
    technicalName: "Соус с яблоком и специями (тыквенный)",
    page: 704,
    day: 15,
    week: "Неделя 3 (соусы)",
    section: "Комплименты",
  },
  {
    type: "compliment",
    id: 16,
    displayName: "БОБОВО-ТОМАТНЫЙ ДУЭТ",
    technicalName: "Помидорно-перечный соус с чечевицей",
    page: 706,
    day: 16,
    week: "Неделя 3 (соусы)",
    section: "Комплименты",
  },
  {
    type: "compliment",
    id: 17,
    displayName: "ПРОСЫПАЙСЯ!",
    technicalName: "Пряная смесь для утренних каш",
    page: 967,
    day: 17,
    week: "Неделя 4 (смеси специй)",
    section: "Комплименты",
  },
  {
    type: "compliment",
    id: 18,
    displayName: "ТЁПЛЫЙ КОРЕНЬ",
    technicalName: "Смесь для супов",
    page: 969,
    day: 18,
    week: "Неделя 4 (смеси специй)",
    section: "Комплименты",
  },
  {
    type: "compliment",
    id: 19,
    displayName: "БОБОВОЕ СЕРДЦЕ",
    technicalName: "Смесь для бобовых",
    page: 971,
    day: 19,
    week: "Неделя 4 (смеси специй)",
    section: "Комплименты",
  },
  {
    type: "compliment",
    id: 20,
    displayName: "ЖИВАЯ ЗЕЛЕНЬ",
    technicalName: "Смесь для салатов",
    page: 973,
    day: 20,
    week: "Неделя 4 (смеси специй)",
    section: "Комплименты",
  },
  {
    type: "compliment",
    id: 21,
    displayName: "ЗОЛОТАЯ КОРОЧКА",
    technicalName: "Смесь для блинчиков, оладий, запеканок",
    page: 975,
    day: 21,
    week: "Неделя 4 (смеси специй)",
    section: "Комплименты",
  },
  {
    type: "breakfast",
    id: 1,
    displayName: "ОВСЯНКА, СЭР!",
    technicalName: "Овсянка с яблоком, корицей и молотым льном",
    page: 175,
    day: 1,
    week: "Неделя 1",
    section: "Завтраки",
  },
  {
    type: "breakfast",
    id: 2,
    displayName: "САВАННА В ТАРЕЛКЕ",
    technicalName: "Каша из сорго с яблоком",
    page: 210,
    day: 2,
    week: "Неделя 1",
    section: "Завтраки",
  },
  {
    type: "breakfast",
    id: 3,
    displayName: "В ГОСТЯХ У БАБУШКИ",
    technicalName: "Чиа-пудинг с ягодами и блинчики из гречневой муки",
    page: 242,
    day: 3,
    week: "Неделя 1",
    section: "Завтраки",
  },
  {
    type: "breakfast",
    id: 4,
    displayName: "ИГРУШКА ОСЕНИ",
    technicalName: "Каша из амаранта с грушей, корицей и семенами чиа",
    page: 271,
    day: 4,
    week: "Неделя 1",
    section: "Завтраки",
  },
  {
    type: "breakfast",
    id: 5,
    displayName: "ЗАРЯДИСЬ-КА!",
    technicalName: "Киноа-пудинг с яблоком, корицей, рукколой и семенами тыквы",
    page: 303,
    day: 5,
    week: "Неделя 1",
    section: "Завтраки",
  },
  {
    type: "breakfast",
    id: 6,
    displayName: "ГОСТЬ ИЗ МЕКСИКИ",
    technicalName: "Кабачковые оладьи с морковным соусом",
    page: 339,
    day: 6,
    week: "Неделя 1",
    section: "Завтраки",
  },
  {
    type: "breakfast",
    id: 7,
    displayName: "ОРАНЖЕВОЕ НАСТРОЕНИЕ",
    technicalName: "Тыквенные оладьи с яблочным конфитюром и семенами",
    page: 368,
    day: 7,
    week: "Неделя 1",
    section: "Завтраки",
  },
  {
    type: "breakfast",
    id: 8,
    displayName: "МИСТЕР ОЛАДЬЕ",
    technicalName: "Панкейки из зелёной гречки с кунжутно-банановым кремом",
    page: 451,
    day: 8,
    week: "Неделя 2",
    section: "Завтраки",
  },
  {
    type: "breakfast",
    id: 9,
    displayName: "ПШЁНЧИКИ",
    technicalName: "Сырники из пшённой муки с яблоком и малиновым соусом",
    page: 486,
    day: 9,
    week: "Неделя 2",
    section: "Завтраки",
  },
  {
    type: "breakfast",
    id: 10,
    displayName: "ЛАДУШКИ",
    technicalName: "Чечевичные блины с цитрусово-миндальным соусом",
    page: 516,
    day: 10,
    week: "Неделя 2",
    section: "Завтраки",
  },
  {
    type: "breakfast",
    id: 11,
    displayName: "ГРАТЕН АМАРА",
    technicalName: "Запеканка из амаранта с бататом и ягодами",
    page: 545,
    day: 11,
    week: "Неделя 2",
    section: "Завтраки",
  },
  {
    type: "breakfast",
    id: 12,
    displayName: "ОВСЯНЫШ",
    technicalName: "Овсяноблин с ореховым сыром, авокадо, томатами и красным перцем",
    page: 574,
    day: 12,
    week: "Неделя 2",
    section: "Завтраки",
  },
  {
    type: "breakfast",
    id: 13,
    displayName: "КНЯЖЕСКАЯ КАША",
    technicalName: "Гречневая каша с тушёным яблоком и орехово-кунжутной посыпкой",
    page: 612,
    day: 13,
    week: "Неделя 2",
    section: "Завтраки",
  },
  {
    type: "breakfast",
    id: 14,
    displayName: "НЕЖНАЯ СКАЗКА",
    technicalName: "Кремовая овсяно-тыквенная запеканка с кунжутной корочкой и ягодным компотом",
    page: 645,
    day: 14,
    week: "Неделя 2",
    section: "Завтраки",
  },
  {
    type: "breakfast",
    id: 15,
    displayName: "ЧЁРНЫЙ ЖЕМЧУГ",
    technicalName: "Каша из чёрной чечевицы с тушёной грушей и тыквенными семечками",
    page: 724,
    day: 15,
    week: "Неделя 3",
    section: "Завтраки",
  },
  {
    type: "breakfast",
    id: 16,
    displayName: "КРЕМУШКА НЕЖНАЯ",
    technicalName: "Кремовая каша из амаранта с тушёной морковью, яблоком и кунжутом",
    page: 755,
    day: 16,
    week: "Неделя 3",
    section: "Завтраки",
  },
  {
    type: "breakfast",
    id: 17,
    displayName: "ТЕПЛО ПЕРУАНСКОГО УТРА",
    technicalName: "Запеканка из киноа с яблоками и льняным гелем",
    page: 787,
    day: 17,
    week: "Неделя 3",
    section: "Завтраки",
  },
  {
    type: "breakfast",
    id: 18,
    displayName: "ПИСЬМЕЦО ИЗ ДЕТСТВА",
    technicalName: "Блинчики из маша с ягодно-миндальной начинкой",
    page: 819,
    day: 18,
    week: "Неделя 3",
    section: "Завтраки",
  },
  {
    type: "breakfast",
    id: 19,
    displayName: "ПЛЮШЕВЫЕ РАДОСТИ",
    technicalName: "Оладьи из запечённого батата с кешью-соусом",
    page: 854,
    day: 19,
    week: "Неделя 3",
    section: "Завтраки",
  },
  {
    type: "breakfast",
    id: 20,
    displayName: "ЗАВТРАК В ДЕРЕВНЕ",
    technicalName: "Овсяноблин с яблочным джемом",
    page: 887,
    day: 20,
    week: "Неделя 3",
    section: "Завтраки",
  },
  {
    type: "breakfast",
    id: 21,
    displayName: "ТЁПЛЫЙ АККОРД",
    technicalName: "Чечевичная запеканка с помидорами, зеленью и орехово-льняным соусом",
    page: 922,
    day: 21,
    week: "Неделя 3",
    section: "Завтраки",
  },
  {
    type: "breakfast",
    id: 22,
    displayName: "МОРСКОЙ РАССВЕТ",
    technicalName: "Бутерброд с амарантовой лепёшкой",
    page: 997,
    day: 22,
    week: "Неделя 4",
    section: "Завтраки",
  },
  {
    type: "breakfast",
    id: 23,
    displayName: "ВЕСЁЛЫЙ ВЕЛИКАН",
    technicalName: "Бутерброд-конструктор на основе гречневых блинов и паштета из зелёного горошка",
    page: 1038,
    day: 23,
    week: "Неделя 4",
    section: "Завтраки",
  },
  {
    type: "breakfast",
    id: 24,
    displayName: "КРУГЛЯШКИ ТОФИ",
    technicalName: "Тофники с ягодно-миндальным кремом",
    page: 1076,
    day: 24,
    week: "Неделя 4",
    section: "Завтраки",
  },
  {
    type: "breakfast",
    id: 25,
    displayName: "НАРЯДНЫЙ КРАСАВЧИК",
    technicalName: "Сэндвич с печёными перцами и ореховой намазкой",
    page: 1108,
    day: 25,
    week: "Неделя 4",
    section: "Завтраки",
  },
  {
    type: "breakfast",
    id: 26,
    displayName: "НЕОЖИДАННОЕ ГОФРЕ",
    technicalName: "«Вафельный» бутерброд с мексиканским кремовым дипом и тофу",
    page: 1141,
    day: 26,
    week: "Неделя 4",
    section: "Завтраки",
  },
  {
    type: "breakfast",
    id: 27,
    displayName: "СТРАНА БАТАТИЯ",
    technicalName: "Бутерброд на бататовой лепёшке с пастой из белой фасоли и зелёного горошка",
    page: 1180,
    day: 27,
    week: "Неделя 4",
    section: "Завтраки",
  },
  {
    type: "breakfast",
    id: 28,
    displayName: "ОМ-НОМ-НОМ!",
    technicalName: "Тофу-омлет с зеленью, гречневой лепёшкой и свежим салатом",
    page: 1214,
    day: 28,
    week: "Неделя 4",
    section: "Завтраки",
  },
  {
    type: "lunch",
    id: 1,
    displayName: "СУПЧИК КУЧЕРЯВЫЙ",
    technicalName: "Чечевичный суп с овощами и зеленью",
    page: 180,
    day: 1,
    week: "Неделя 1",
    section: "Обеды",
  },
  {
    type: "lunch",
    id: 2,
    displayName: "СОКРОВИЩЕ ИНКОВ",
    technicalName: "Киноа с тушеной капустой, луком и томатами",
    page: 215,
    day: 2,
    week: "Неделя 1",
    section: "Обеды",
  },
  {
    type: "lunch",
    id: 3,
    displayName: "ЗОЛОТЫЕ РОССЫПИ",
    technicalName: "Пшено с тушёной морковью, луком и куркумой",
    page: 247,
    day: 3,
    week: "Неделя 1",
    section: "Обеды",
  },
  {
    type: "lunch",
    id: 4,
    displayName: "СИЛА ВКУСА",
    technicalName: "Нутовый омлет с овощами и ароматными специями",
    page: 276,
    day: 4,
    week: "Неделя 1",
    section: "Обеды",
  },
  {
    type: "lunch",
    id: 5,
    displayName: "СОЛО НА БАРАБАНЕ",
    technicalName: "Овощная солянка с белой фасолью и лимоном",
    page: 307,
    day: 5,
    week: "Неделя 1",
    section: "Обеды",
  },
  {
    type: "lunch",
    id: 6,
    displayName: "С ПРИВЕТОМ ИЗ ИНДИИ",
    technicalName: "Карри с машем, грибами, бататом и домашним кокосовым молоком",
    page: 344,
    day: 6,
    week: "Неделя 1",
    section: "Обеды",
  },
  {
    type: "lunch",
    id: 7,
    displayName: "СЫТНЫЙ",
    technicalName: "Овощной борщ",
    page: 373,
    day: 7,
    week: "Неделя 1",
    section: "Обеды",
  },
  {
    type: "lunch",
    id: 8,
    displayName: "ВОСТОЧНЫЙ АКЦЕНТ",
    technicalName: "Наваристый суп из капусты, нута, тыквы и авокадо",
    page: 455,
    day: 8,
    week: "Неделя 2",
    section: "Обеды",
  },
  {
    type: "lunch",
    id: 9,
    displayName: "КЛЁЦКИ В КРАСНОМ",
    technicalName: "Густой суп из красной фасоли с клёцками из нутовой муки и овощами",
    page: 490,
    day: 9,
    week: "Неделя 2",
    section: "Обеды",
  },
  {
    type: "lunch",
    id: 10,
    displayName: "ОЧЕНЬ ВАЖНЫЙ ПЕРЕЦ!",
    technicalName: "Фаршированные красные перцы по-мексикански с киноа, чёрной фасолью и кукурузой",
    page: 521,
    day: 10,
    week: "Неделя 2",
    section: "Обеды",
  },
  {
    type: "lunch",
    id: 11,
    displayName: "ЖЁЛТЫЙ БАРХАТ",
    technicalName: "Суп-пюре из жёлтого гороха с овощами и зеленью",
    page: 549,
    day: 11,
    week: "Неделя 2",
    section: "Обеды",
  },
  {
    type: "lunch",
    id: 12,
    displayName: "КОСТЕРОК В ТАРЕЛКЕ",
    technicalName: "Капустняк с «дымком», пшеном и лепёшкой из нутовой муки",
    page: 579,
    day: 12,
    week: "Неделя 2",
    section: "Обеды",
  },
  {
    type: "lunch",
    id: 13,
    displayName: "ПРЯНАЯ ФИЕСТА",
    technicalName: "Мексиканское овощное рагу с чечевицей и кукурузой",
    page: 617,
    day: 13,
    week: "Неделя 2",
    section: "Обеды",
  },
  {
    type: "lunch",
    id: 14,
    displayName: "ЛЕНИВЧИКИ ИЗЯЩНЫЕ",
    technicalName: "Ленивые голубцы из бурого риса и овощей в томатно-имбирном соусе",
    page: 650,
    day: 14,
    week: "Неделя 2",
    section: "Обеды",
  },
  {
    type: "lunch",
    id: 15,
    displayName: "ИТАЛЬЯНО",
    technicalName: "Минестроне с белой фасолью, пастернаком и авокадо",
    page: 728,
    day: 15,
    week: "Неделя 3",
    section: "Обеды",
  },
  {
    type: "lunch",
    id: 16,
    displayName: "ВЕЛЮР-ФОНДЮ",
    technicalName: "«Сырный» суп с нутом, брокколи и тыквой",
    page: 759,
    day: 16,
    week: "Неделя 3",
    section: "Обеды",
  },
  {
    type: "lunch",
    id: 17,
    displayName: "ИСТИНА В ЗЕРНЕ",
    technicalName: "Плов из чёрного риса с баклажаном, томатами и зеленью",
    page: 792,
    day: 17,
    week: "Неделя 3",
    section: "Обеды",
  },
  {
    type: "lunch",
    id: 18,
    displayName: "ЖАРКИЙ ГЕРОЙ",
    technicalName: "Чили из белой фасоли и корня сельдерея",
    page: 824,
    day: 18,
    week: "Неделя 3",
    section: "Обеды",
  },
  {
    type: "lunch",
    id: 19,
    displayName: "ЕГИПЕТ РЯДОМ...",
    technicalName: "Фалафель из коричневой чечевицы в томатной подливе с авокадо",
    page: 858,
    day: 19,
    week: "Неделя 3",
    section: "Обеды",
  },
  {
    type: "lunch",
    id: 20,
    displayName: "С ПРИВКУСОМ МУМБАИ",
    technicalName: "Чана масала",
    page: 892,
    day: 20,
    week: "Неделя 3",
    section: "Обеды",
  },
  {
    type: "lunch",
    id: 21,
    displayName: "ГРЕЧА-ПЕЧЕРИЦА",
    technicalName: "Зелёная гречка с грибами, морковью и салатом из краснокочанной капусты",
    page: 927,
    day: 21,
    week: "Неделя 3",
    section: "Обеды",
  },
  {
    type: "lunch",
    id: 22,
    displayName: "РОДОМ ИЗ ЛУИЗИАНЫ",
    technicalName: "Гамбо из овощей и чёрной фасоли",
    page: 1002,
    day: 22,
    week: "Неделя 4",
    section: "Обеды",
  },
  {
    type: "lunch",
    id: 23,
    displayName: "ДЕРЕВЕНСКИЙ ФЛЁР",
    technicalName: "Щи с квашеной капустой, бурым рисом и грибами",
    page: 1043,
    day: 23,
    week: "Неделя 4",
    section: "Обеды",
  },
  {
    type: "lunch",
    id: 24,
    displayName: "ЗЛАТОЦВЕТ",
    technicalName: "Цветная капуста с карри и зелёной чечевицей",
    page: 1081,
    day: 24,
    week: "Неделя 4",
    section: "Обеды",
  },
  {
    type: "lunch",
    id: 25,
    displayName: "ЯРКИЙ АКЦЕНТ",
    technicalName: "Суп-пюре из сорго с морковью и бататом",
    page: 1113,
    day: 25,
    week: "Неделя 4",
    section: "Обеды",
  },
  {
    type: "lunch",
    id: 26,
    displayName: "КЛАДЕЗЬ ПОЛЬЗЫ",
    technicalName: "Золотой слоёный пирог из овощей и бобовых",
    page: 1146,
    day: 26,
    week: "Неделя 4",
    section: "Обеды",
  },
  {
    type: "lunch",
    id: 27,
    displayName: "ОГОНЬ СТЕПЕЙ",
    technicalName: "Пряный суп с овощами и пшеном",
    page: 1185,
    day: 27,
    week: "Неделя 4",
    section: "Обеды",
  },
  {
    type: "lunch",
    id: 28,
    displayName: "БОГАТЫРСКИЕ",
    technicalName: "Нутовые котлеты с соусом «Мухаммара» и свежим салатом",
    page: 1220,
    day: 28,
    week: "Неделя 4",
    section: "Обеды",
  },
  {
    type: "dinner",
    id: 1,
    displayName: "ЯНТАРНАЯ ШКАТУЛКА",
    technicalName: "Запечённый батат с нутом и зелёным салатом",
    page: 188,
    day: 1,
    week: "Неделя 1",
    section: "Ужины",
  },
  {
    type: "dinner",
    id: 2,
    displayName: "ОДНА В ЛОДКЕ",
    technicalName: "Запечённые баклажаны с фасолевым паштетом и зелёным салатом",
    page: 220,
    day: 2,
    week: "Неделя 1",
    section: "Ужины",
  },
  {
    type: "dinner",
    id: 3,
    displayName: "НОЧНОЙ ЭКСПРЕСС",
    technicalName: "Свекольно-морковные котлетки с зелёным соусом и салатом из капусты",
    page: 251,
    day: 3,
    week: "Неделя 1",
    section: "Ужины",
  },
  {
    type: "dinner",
    id: 4,
    displayName: "МОЛОДО-ЗЕЛЕНО",
    technicalName: "Тушёные кабачки с зелёным горошком и базиликом",
    page: 281,
    day: 4,
    week: "Неделя 1",
    section: "Ужины",
  },
  {
    type: "dinner",
    id: 5,
    displayName: "ДОМИК КУМА ТЫКВЫ",
    technicalName: "Тушёная тыква с куркумой, луком и зеленью",
    page: 312,
    day: 5,
    week: "Неделя 1",
    section: "Ужины",
  },
  {
    type: "dinner",
    id: 6,
    displayName: "РУБИНОВЫЙ ЗАКАТ",
    technicalName: "Запечённая свёкла с красным перцем, кукурузой и соусом из рукколы и кешью",
    page: 349,
    day: 6,
    week: "Неделя 1",
    section: "Ужины",
  },
  {
    type: "dinner",
    id: 7,
    displayName: "ОБМАНИ МЕНЯ!",
    technicalName: "Рис из цветной капусты с чечевицей, острым томатным соусом и зеленью",
    page: 378,
    day: 7,
    week: "Неделя 1",
    section: "Ужины",
  },
  {
    type: "dinner",
    id: 8,
    displayName: "ЗЕЛЁНЫЕ МАКУШКИ",
    technicalName: "Овощная запеканка с брокколи, цукини, томатами и сорго",
    page: 459,
    day: 8,
    week: "Неделя 2",
    section: "Ужины",
  },
  {
    type: "dinner",
    id: 9,
    displayName: "РИСУЛЯ РЫЖИЙ",
    technicalName: "Тушёный бурый рис с тыквой, шпинатом и томатно-имбирной заправкой",
    page: 495,
    day: 9,
    week: "Неделя 2",
    section: "Ужины",
  },
  {
    type: "dinner",
    id: 10,
    displayName: "ГРИБЫ НА ПОДУШКЕ",
    technicalName: "Пюре из цветной капусты с шампиньонами и морковно-зелёным салатом",
    page: 526,
    day: 10,
    week: "Неделя 2",
    section: "Ужины",
  },
  {
    type: "dinner",
    id: 11,
    displayName: "ПЕРСИДСКИЙ НАПЕВ",
    technicalName: "Свёкла с брокколи и машем, под гранатовой посыпкой",
    page: 554,
    day: 11,
    week: "Неделя 2",
    section: "Ужины",
  },
  {
    type: "dinner",
    id: 12,
    displayName: "РАЗВЕСЁЛЫЙ КАРНАВАЛ",
    technicalName: "Рагу со стручковой фасолью",
    page: 584,
    day: 12,
    week: "Неделя 2",
    section: "Ужины",
  },
  {
    type: "dinner",
    id: 13,
    displayName: "КЛАД ФЛАНДРИИ",
    technicalName: "Запечённая брюссельская капуста с морковью, красной фасолью и крем-соусом",
    page: 622,
    day: 13,
    week: "Неделя 2",
    section: "Ужины",
  },
  {
    type: "dinner",
    id: 14,
    displayName: "ТРИО ПОД ЗЕЛЕНЬЮ",
    technicalName: "Запечённый батат с тушёными грибами и шпинатом",
    page: 655,
    day: 14,
    week: "Неделя 2",
    section: "Ужины",
  },
  {
    type: "dinner",
    id: 15,
    displayName: "КНЕЛИ ПОД ШУБКОЙ",
    technicalName: "Тефтели из маша с зеленью и крем-соусом",
    page: 733,
    day: 15,
    week: "Неделя 3",
    section: "Ужины",
  },
  {
    type: "dinner",
    id: 16,
    displayName: "ЗЕМЛЯ И СОЛНЦЕ",
    technicalName: "Свёкла с кукурузой и крем-соусом из кешью",
    page: 764,
    day: 16,
    week: "Неделя 3",
    section: "Ужины",
  },
  {
    type: "dinner",
    id: 17,
    displayName: "КУДРЯШКА С МЕДАЛЬОНАМИ",
    technicalName: "Кабачки с цветной капустой, бататом и соусом",
    page: 797,
    day: 17,
    week: "Неделя 3",
    section: "Ужины",
  },
  {
    type: "dinner",
    id: 18,
    displayName: "А В КАРМАШКАХ - ЗОЛОТО!",
    technicalName: "Капустные кармашки с амарантом, жёлтым перцем и томатно-имбирной заливкой",
    page: 829,
    day: 18,
    week: "Неделя 3",
    section: "Ужины",
  },
  {
    type: "dinner",
    id: 19,
    displayName: "НАСЛЕДИЕ МОНГОЛОВ",
    technicalName: "Котлетки из пшена с морковью и красным перцем",
    page: 862,
    day: 19,
    week: "Неделя 3",
    section: "Ужины",
  },
  {
    type: "dinner",
    id: 20,
    displayName: "МАДАМ БРЮСЕЛЬЕ",
    technicalName: "Брюссельская капуста с грецкими орехами и свекольным хумусом",
    page: 896,
    day: 20,
    week: "Неделя 3",
    section: "Ужины",
  },
  {
    type: "dinner",
    id: 21,
    displayName: "ФАНТАЗИИ НА ТЕМУ...",
    technicalName: "Винегрет с машем, ферментированной капустой и киноа-лепёшками",
    page: 933,
    day: 21,
    week: "Неделя 3",
    section: "Ужины",
  },
  {
    type: "dinner",
    id: 22,
    displayName: "КАПУСТА И ВСЕ, ВСЕ, ВСЕ...",
    technicalName: "Запеканка из капусты с нутовым «кремом», мисо и овощами",
    page: 1007,
    day: 22,
    week: "Неделя 4",
    section: "Ужины",
  },
  {
    type: "dinner",
    id: 23,
    displayName: "АДЖАПСАНДАЛ",
    technicalName: "Запечённые овощи с соусом «Огненный поцелуй»",
    page: 1048,
    day: 23,
    week: "Неделя 4",
    section: "Ужины",
  },
  {
    type: "dinner",
    id: 24,
    displayName: "НЕЖНЫЙ ЗАКАТ",
    technicalName: "Запечённая тыква в соусе из белой фасоли",
    page: 1086,
    day: 24,
    week: "Неделя 4",
    section: "Ужины",
  },
  {
    type: "dinner",
    id: 25,
    displayName: "АРОМАТНЫЙ БРИЗ",
    technicalName: "Пюре из запечённого сельдерея и тыквы с крем-соусом и свежим салатом",
    page: 1118,
    day: 25,
    week: "Неделя 4",
    section: "Ужины",
  },
  {
    type: "dinner",
    id: 26,
    displayName: "ЧЕРВОННЫЙ ЛЕС",
    technicalName: "Свёкла с грибами, ореховым кремом и амарантовой лепёшкой",
    page: 1151,
    day: 26,
    week: "Неделя 4",
    section: "Ужины",
  },
  {
    type: "dinner",
    id: 27,
    displayName: "СВЕТ И ТЕНЬ",
    technicalName: "Соте из овощей и чёрной чечевицы с кешью-кремом",
    page: 1190,
    day: 27,
    week: "Неделя 4",
    section: "Ужины",
  },
  {
    type: "dinner",
    id: 28,
    displayName: "ПРИВЕТ ФРАНЦУЗУ!",
    technicalName: "Веганский «Оливье» с «яйцами» из цветной капусты и «колбасой» из свёклы",
    page: 1225,
    day: 28,
    week: "Неделя 4",
    section: "Ужины",
  },
  {
    type: "recipe_day",
    id: 1,
    displayName: "ПАСТЕЛЬНЫЕ МЕЧТЫ",
    technicalName: "Гречневый хлеб",
    page: 193,
    day: 1,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 2,
    displayName: "ПРОСТАЯ ИСТОРИЯ",
    technicalName: "Вафли зелёные универсальные (безглютеновые из чечевицы)",
    page: 226,
    day: 2,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 3,
    displayName: "УТРЕННИЙ КОЛОВОРОТ",
    technicalName: "Тарт с яблоками и корицей",
    page: 256,
    day: 3,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 4,
    displayName: "ВОЛШЕБНАЯ ДЕВЯТКА",
    technicalName: "Полезная гранола",
    page: 286,
    day: 4,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 5,
    displayName: "КВАРТЕТ МАЛЫШЕЙ",
    technicalName: "Хлебцы из семян",
    page: 317,
    day: 5,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 6,
    displayName: "И СОВЕСТЬ ЧИСТА!",
    technicalName: "Кексы из гречневой муки с бананами, апельсином и псиллиумом",
    page: 354,
    day: 6,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 7,
    displayName: "ПУХЛЯШИ-ДОБРЯШИ",
    technicalName: "Пампушки из гречневой муки с чесноком и зеленью",
    page: 383,
    day: 7,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 8,
    displayName: "ВЕРТУШКИ-ЗАВИТУШКИ",
    technicalName: "Синнабоны с финиковой пастой",
    page: 463,
    day: 8,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 9,
    displayName: "АПЕЛЬСИНОВЫЕ БАТАТИКИ",
    technicalName: "Печенье из запечённого батата с семечками и цитрусовой нотой",
    page: 499,
    day: 9,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 10,
    displayName: "АКВА - ВИТА",
    technicalName: "Аквафаба из варёного нута",
    page: 531,
    day: 10,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 11,
    displayName: "Кетчуп цельный (без сахара)",
    technicalName: "Кетчуп цельный (без сахара)",
    page: 558,
    day: 11,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 12,
    displayName: "Майонез на белой фасоли",
    technicalName: "Майонез на белой фасоли",
    page: 559,
    day: 11,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 13,
    displayName: "Майонез на аквафабе",
    technicalName: "Майонез на аквафабе",
    page: 559,
    day: 11,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 14,
    displayName: "Горчица из цельных семян",
    technicalName: "Горчица из цельных семян",
    page: 560,
    day: 11,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 15,
    displayName: "ЯГОДКА ОПЯТЬ",
    technicalName: "Ягодный джем (классический)",
    page: 589,
    day: 12,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 16,
    displayName: "ЯГОДКА ОПЯТЬ",
    technicalName: "Ягодный джем (сырой с чиа)",
    page: 590,
    day: 12,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 17,
    displayName: "БОРДОШ ВКУСНЫЙ",
    technicalName: "Свекольный брауни",
    page: 627,
    day: 13,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 18,
    displayName: "ШАРЛАТАНКА",
    technicalName: "Безглютеновая шарлотка",
    page: 660,
    day: 14,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 19,
    displayName: "СЕЗАМ, ОТКРОЙСЯ!",
    technicalName: "Кунжутное печенье с финиками, корицей и апельсиновой цедрой",
    page: 738,
    day: 15,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 20,
    displayName: "ШЕПОТ ФЕИ",
    technicalName: "Запечённые яблоки с грушей, чиа и клюквенным соусом",
    page: 769,
    day: 16,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 21,
    displayName: "ЛЕТО В КОРЗИНКЕ",
    technicalName: "Мини-тарты с ягодами и орехово-финиковой основой",
    page: 802,
    day: 17,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 22,
    displayName: "ШЁЛКОВЫЙ ПУТЬ",
    technicalName: "Миндальная паста (цельная)",
    page: 834,
    day: 18,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 23,
    displayName: "ШЁЛКОВЫЙ ПУТЬ",
    technicalName: "Кешью-паста (цельная)",
    page: 835,
    day: 18,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 24,
    displayName: "ШЁЛКОВЫЙ ПУТЬ",
    technicalName: "Паста из грецких орехов",
    page: 836,
    day: 18,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 25,
    displayName: "Цельная «Нутелла»",
    technicalName: "Цельная «Нутелла»",
    page: 837,
    day: 18,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 26,
    displayName: "ЯГОДЫ В ШОКЕ!",
    technicalName: "Ягодно-шоколадный пудинг с семенами чиа",
    page: 867,
    day: 19,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 27,
    displayName: "КОЛЕСО ФОРТУНЫ",
    technicalName: "Апельсиновый торт",
    page: 901,
    day: 20,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 28,
    displayName: "ФИОЛЕТОВОЕ НАСТРОЕНИЕ",
    technicalName: "Пирог без выпечки",
    page: 938,
    day: 21,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 29,
    displayName: "УМНЫЙ ТОФУ",
    technicalName: "Тофу домашний",
    page: 1013,
    day: 22,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 30,
    displayName: "Ферментированный сливочный миндальный сыр",
    technicalName: "Ферментированный сливочный миндальный сыр",
    page: 1054,
    day: 23,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 31,
    displayName: "ТРИ В ОДНОМ",
    technicalName: "Хлеб из муки зелёной гречки, бурого риса и нута",
    page: 1090,
    day: 24,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 32,
    displayName: "МОЯ ПРЕЛЕСТЬ!",
    technicalName: "Морковно-финиковое «печенье» с ванилью",
    page: 1123,
    day: 25,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 33,
    displayName: "Хумус «Классический»",
    technicalName: "Хумус «Классический»",
    page: 1159,
    day: 26,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 34,
    displayName: "Хумус «Железный»",
    technicalName: "Хумус «Железный»",
    page: 1160,
    day: 26,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 35,
    displayName: "Хумус «Тихий»",
    technicalName: "Хумус «Тихий»",
    page: 1161,
    day: 26,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 36,
    displayName: "Хумус «Ясный»",
    technicalName: "Хумус «Ясный»",
    page: 1162,
    day: 26,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 37,
    displayName: "Хумус «Сердечный»",
    technicalName: "Хумус «Сердечный»",
    page: 1163,
    day: 26,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 38,
    displayName: "Хумус «Солнечный»",
    technicalName: "Хумус «Солнечный»",
    page: 1164,
    day: 26,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 39,
    displayName: "Хумус «Весенний»",
    technicalName: "Хумус «Весенний»",
    page: 1165,
    day: 26,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 40,
    displayName: "АННАПУРНА",
    technicalName: "Пицца",
    page: 1195,
    day: 27,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "recipe_day",
    id: 41,
    displayName: "ДАР СВАРОГА",
    technicalName: "Пшённый хлеб",
    page: 1231,
    day: 28,
    week: "Рецепт дня",
    section: "Рецепты дня",
  },
  {
    type: "drinks",
    id: 1,
    displayName: "Имбирный заряд",
    technicalName: "Имбирный заряд",
    page: 201,
    day: 1,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 2,
    displayName: "Ясность",
    technicalName: "Ясность",
    page: 202,
    day: 1,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 3,
    displayName: "Сладкий сон",
    technicalName: "Сладкий сон",
    page: 203,
    day: 1,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "drinks",
    id: 4,
    displayName: "Цитрусовый пробег",
    technicalName: "Цитрусовый пробег",
    page: 230,
    day: 2,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 5,
    displayName: "ЖКТ-комфорт",
    technicalName: "ЖКТ-комфорт",
    page: 231,
    day: 2,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 6,
    displayName: "Вечерний уют",
    technicalName: "Вечерний уют",
    page: 233,
    day: 2,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "drinks",
    id: 7,
    displayName: "Пряный восход",
    technicalName: "Пряный восход",
    page: 261,
    day: 3,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 8,
    displayName: "Травяной баланс",
    technicalName: "Травяной баланс",
    page: 262,
    day: 3,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 9,
    displayName: "Облако",
    technicalName: "Облако",
    page: 263,
    day: 3,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "drinks",
    id: 10,
    displayName: "Золотое утро",
    technicalName: "Золотое утро",
    page: 291,
    day: 4,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 11,
    displayName: "Обеденный ритм",
    technicalName: "Обеденный ритм",
    page: 292,
    day: 4,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 12,
    displayName: "Тихий час",
    technicalName: "Тихий час",
    page: 293,
    day: 4,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "drinks",
    id: 13,
    displayName: "Бодрящий микс",
    technicalName: "Бодрящий микс",
    page: 322,
    day: 5,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 14,
    displayName: "Свежий ум",
    technicalName: "Свежий ум",
    page: 323,
    day: 5,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 15,
    displayName: "Умиротворение",
    technicalName: "Умиротворение",
    page: 324,
    day: 5,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "drinks",
    id: 16,
    displayName: "Травяная свежесть",
    technicalName: "Травяная свежесть",
    page: 358,
    day: 6,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 17,
    displayName: "Сбалансированный полдень",
    technicalName: "Сбалансированный полдень",
    page: 359,
    day: 6,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 18,
    displayName: "Вечернее настроение",
    technicalName: "Вечернее настроение",
    page: 360,
    day: 6,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "drinks",
    id: 19,
    displayName: "Утренний ветерок",
    technicalName: "Утренний ветерок",
    page: 388,
    day: 7,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 20,
    displayName: "Ясное спокойствие",
    technicalName: "Ясное спокойствие",
    page: 389,
    day: 7,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 21,
    displayName: "Безмятежность",
    technicalName: "Безмятежность",
    page: 390,
    day: 7,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "drinks",
    id: 22,
    displayName: "Ягодный рассвет",
    technicalName: "Ягодный рассвет",
    page: 468,
    day: 8,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 23,
    displayName: "Лимонно-травяной баланс",
    technicalName: "Лимонно-травяной баланс",
    page: 469,
    day: 8,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 24,
    displayName: "Тихий омут",
    technicalName: "Тихий омут",
    page: 470,
    day: 8,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "drinks",
    id: 25,
    displayName: "Солнечный эликсир",
    technicalName: "Солнечный эликсир",
    page: 504,
    day: 9,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 26,
    displayName: "Лёгкость бытия",
    technicalName: "Лёгкость бытия",
    page: 505,
    day: 9,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 27,
    displayName: "Сонные травы",
    technicalName: "Сонные травы",
    page: 506,
    day: 9,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "drinks",
    id: 28,
    displayName: "Лимонно-куркумовый заряд",
    technicalName: "Лимонно-куркумовый заряд",
    page: 534,
    day: 10,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 29,
    displayName: "Травяной антиоксидант",
    technicalName: "Травяной антиоксидант",
    page: 535,
    day: 10,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 30,
    displayName: "Восстанавливающий шиповник",
    technicalName: "Восстанавливающий шиповник",
    page: 536,
    day: 10,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "drinks",
    id: 31,
    displayName: "Травяная свежесть",
    technicalName: "Травяная свежесть",
    page: 562,
    day: 11,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 32,
    displayName: "Лимонная свежесть",
    technicalName: "Лимонная свежесть",
    page: 563,
    day: 11,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 33,
    displayName: "Степной покой",
    technicalName: "Степной покой",
    page: 564,
    day: 11,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "drinks",
    id: 34,
    displayName: "Пряный заряд с апельсином",
    technicalName: "Пряный заряд с апельсином",
    page: 594,
    day: 12,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 35,
    displayName: "Яблочно-травяной баланс",
    technicalName: "Яблочно-травяной баланс",
    page: 595,
    day: 12,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 36,
    displayName: "Спите вкусно",
    technicalName: "Спите вкусно",
    page: 596,
    day: 12,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "drinks",
    id: 37,
    displayName: "Янтарный восход",
    technicalName: "Янтарный восход",
    page: 634,
    day: 13,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 38,
    displayName: "Средиземноморский бриз",
    technicalName: "Средиземноморский бриз",
    page: 635,
    day: 13,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 39,
    displayName: "Шёлковое расслабление",
    technicalName: "Шёлковое расслабление",
    page: 636,
    day: 13,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "drinks",
    id: 40,
    displayName: "Ягодный тонус",
    technicalName: "Ягодный тонус",
    page: 664,
    day: 14,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 41,
    displayName: "Витаминный холодный настой",
    technicalName: "Витаминный холодный настой",
    page: 665,
    day: 14,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 42,
    displayName: "Миндальный покой",
    technicalName: "Миндальный покой",
    page: 666,
    day: 14,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "drinks",
    id: 43,
    displayName: "Дальневосточный заряд",
    technicalName: "Дальневосточный заряд",
    page: 743,
    day: 15,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 44,
    displayName: "Желудочный сбор",
    technicalName: "Желудочный сбор",
    page: 744,
    day: 15,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 45,
    displayName: "Цветочная нега",
    technicalName: "Цветочная нега",
    page: 745,
    day: 15,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "drinks",
    id: 46,
    displayName: "Асафетидовый тоник",
    technicalName: "Асафетидовый тоник",
    page: 774,
    day: 16,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 47,
    displayName: "Фенхелевый холодник",
    technicalName: "Фенхелевый холодник",
    page: 775,
    day: 16,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 48,
    displayName: "Пробиотический покой",
    technicalName: "Пробиотический покой",
    page: 776,
    day: 16,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "drinks",
    id: 49,
    displayName: "Облепихово-пряный заряд",
    technicalName: "Облепихово-пряный заряд",
    page: 807,
    day: 17,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 50,
    displayName: "Печёночный щит",
    technicalName: "Печёночный щит",
    page: 808,
    day: 17,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 51,
    displayName: "Укропное успокоение",
    technicalName: "Укропное успокоение",
    page: 809,
    day: 17,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "drinks",
    id: 52,
    displayName: "Гепато-тоник",
    technicalName: "Гепато-тоник",
    page: 839,
    day: 18,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 53,
    displayName: "Зелёный детокс-настой",
    technicalName: "Зелёный детокс-настой",
    page: 840,
    day: 18,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 54,
    displayName: "Шиповниковый глинтвейн",
    technicalName: "Шиповниковый глинтвейн",
    page: 841,
    day: 18,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "drinks",
    id: 55,
    displayName: "Клюквенный заряд",
    technicalName: "Клюквенный заряд",
    page: 871,
    day: 19,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 56,
    displayName: "Ройбуш с мелиссой",
    technicalName: "Ройбуш с мелиссой",
    page: 872,
    day: 19,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 57,
    displayName: "Золотое молоко",
    technicalName: "Золотое молоко",
    page: 873,
    day: 19,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "drinks",
    id: 58,
    displayName: "Артишоковый старт",
    technicalName: "Артишоковый старт",
    page: 907,
    day: 20,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 59,
    displayName: "Зверобойно-мятная ясность",
    technicalName: "Зверобойно-мятная ясность",
    page: 908,
    day: 20,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 60,
    displayName: "Вишнёвый покой",
    technicalName: "Вишнёвый покой",
    page: 909,
    day: 20,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "drinks",
    id: 61,
    displayName: "Пряный адаптогенный чай",
    technicalName: "Пряный адаптогенный чай",
    page: 942,
    day: 21,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 62,
    displayName: "Витаминный микс с облепихой",
    technicalName: "Витаминный микс с облепихой",
    page: 943,
    day: 21,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 63,
    displayName: "Рябиново-имбирный настой",
    technicalName: "Рябиново-имбирный настой",
    page: 944,
    day: 21,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "drinks",
    id: 64,
    displayName: "Цикорно-пряный тоник",
    technicalName: "Цикорно-пряный тоник",
    page: 1021,
    day: 22,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 65,
    displayName: "Чернично-мятная свежесть",
    technicalName: "Чернично-мятная свежесть",
    page: 1022,
    day: 22,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 66,
    displayName: "Липово-лавандовая нега",
    technicalName: "Липово-лавандовая нега",
    page: 1023,
    day: 22,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "drinks",
    id: 67,
    displayName: "Зира-апельсиновый рассвет",
    technicalName: "Зира-апельсиновый рассвет",
    page: 1060,
    day: 23,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 68,
    displayName: "Гинкго-лимонный фокус",
    technicalName: "Гинкго-лимонный фокус",
    page: 1061,
    day: 23,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 70,
    displayName: "Бузинный сон",
    technicalName: "Бузинный сон",
    page: 1062,
    day: 23,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "drinks",
    id: 71,
    displayName: "Пажитниковый тоник",
    technicalName: "Пажитниковый тоник",
    page: 1096,
    day: 24,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 72,
    displayName: "Эстрагоновый фреш",
    technicalName: "Эстрагоновый фреш",
    page: 1097,
    day: 24,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 73,
    displayName: "Дягилевый сон",
    technicalName: "Дягилевый сон",
    page: 1098,
    day: 24,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "drinks",
    id: 74,
    displayName: "Корень лопуха с имбирём",
    technicalName: "Корень лопуха с имбирём",
    page: 1128,
    day: 25,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 75,
    displayName: "Таволговый чай с мятой",
    technicalName: "Таволговый чай с мятой",
    page: 1129,
    day: 25,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 76,
    displayName: "Котовниковый сон",
    technicalName: "Котовниковый сон",
    page: 1130,
    day: 25,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "drinks",
    id: 77,
    displayName: "Ирговый рассвет",
    technicalName: "Ирговый рассвет",
    page: 1167,
    day: 26,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 78,
    displayName: "Родиоловый фокус",
    technicalName: "Родиоловый фокус",
    page: 1168,
    day: 26,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 79,
    displayName: "Сумерки",
    technicalName: "Сумерки",
    page: 1169,
    day: 26,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "drinks",
    id: 80,
    displayName: "Аирный тоник",
    technicalName: "Аирный тоник",
    page: 1202,
    day: 27,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 81,
    displayName: "Эхинацея-шиповник",
    technicalName: "Эхинацея-шиповник",
    page: 1203,
    day: 27,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 82,
    displayName: "Шлемниковый сон",
    technicalName: "Шлемниковый сон",
    page: 1204,
    day: 27,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "drinks",
    id: 83,
    displayName: "Апельсиново-имбирный тоник",
    technicalName: "Апельсиново-имбирный тоник",
    page: 1236,
    day: 28,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Утро",
  },
  {
    type: "drinks",
    id: 84,
    displayName: "Базиликово-мятный освежающий настой",
    technicalName: "Базиликово-мятный освежающий настой",
    page: 1237,
    day: 28,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "День",
  },
  {
    type: "drinks",
    id: 85,
    displayName: "Валерианово-лавандовый сон",
    technicalName: "Валерианово-лавандовый сон",
    page: 1238,
    day: 28,
    week: "Напиток дня",
    section: "Напитки",
    timeOfDay: "Вечер",
  },
  {
    type: "must_have",
    id: 1,
    displayName: "ОЧЕНЬ ВКУСНЫЕ ДЕЛА!",
    technicalName: "Домашний йогурт из кешью с пробиотиками",
    page: 161,
    day: 1,
    week: "Неделя 1",
    section: "Must Have",
  },
  {
    type: "must_have",
    id: 2,
    displayName: "ВЕЧЕР В ПРОСТОКВАШИНО",
    technicalName: "Квашеная капуста с морковью и яблоком",
    page: 167,
    day: 2,
    week: "Неделя 1",
    section: "Must Have",
  },
  {
    type: "must_have",
    id: 3,
    displayName: "Пробиотическое овощное ассорти (с куркумой и имбирём)",
    technicalName: "Пробиотическое овощное ассорти (с куркумой и имбирём)",
    page: 437,
    day: 3,
    week: "Неделя 2",
    section: "Must Have",
  },
  {
    type: "must_have",
    id: 4,
    displayName: "Домашний миндально-кешью йогурт с ванилью и корицей",
    technicalName: "Домашний миндально-кешью йогурт с ванилью и корицей",
    page: 441,
    day: 4,
    week: "Неделя 2",
    section: "Must Have",
  },
  {
    type: "must_have",
    id: 5,
    displayName: "Проростки (бобовые, злаки, семена)",
    technicalName: "Проростки (бобовые, злаки, семена)",
    page: 445,
    day: 5,
    week: "Неделя 2",
    section: "Must Have",
    kind: "technical",
  },
  {
    type: "must_have",
    id: 6,
    displayName: "Мисо-паста (ферментированная)",
    technicalName: "Мисо-паста (ферментированная)",
    page: 715,
    day: 6,
    week: "Неделя 3",
    section: "Must Have",
    kind: "technical",
  },
  {
    type: "must_have",
    id: 7,
    displayName: "ПОЛНЫЙ АМИНОКИСЛОТНЫЙ ПРОФИЛЬ",
    technicalName: "Домашняя протеиновая смесь",
    page: 980,
    day: 7,
    week: "Неделя 4",
    section: "Must Have",
    kind: "technical",
  },
  {
    type: "must_have",
    id: 8,
    displayName: "УМНАЯ НАСЫЩАЮЩАЯ МАТРИЦА",
    technicalName: "Смесь клетчатки",
    page: 983,
    day: 8,
    week: "Неделя 4",
    section: "Must Have",
  },
];