// Diary type contracts for the Personal Diary module

/**
 * Origin of a diary entry indicating its source module
 */
export type DiaryEntryOrigin =
  | "thoughts"      // Manual user thoughts
  | "water"         // Water tracking
  | "food"          // Food/nutrition tracking
  | "movement"      // Physical activity
  | "sleep"         // Sleep tracking
  | "measurements"  // Body measurements
  | "digestion"     // Digestion tracking
  | "purchases"     // Shopping/purchases
  | "habits"        // Habit tracking
  | "recipes"       // Recipe usage
  | "daily_rating"  // Daily rating
  | "system";       // System-generated entries

/**
 * Source of a timeline item indicating how it was added
 */
export type DiaryTimelineSource =
  | "manual"        // User-created entry
  | "derived"       // Derived from other module data
  | "system";       // Generated by system

/**
 * Individual timeline item in the diary
 */
export interface DiaryTimelineItem {
  id: string;                           // Unique identifier
  text: string;                         // Main content text
  time: string;                         // Display time (HH:MM format)
  machineTimestamp?: string;            // Optional precise timestamp for sorting
  origin: DiaryEntryOrigin;             // Source module
  source: DiaryTimelineSource;          // How the item was added
  thumbnail?: DiaryThumbnail;           // Optional thumbnail metadata
  canDelete: boolean;                   // Whether user can delete this item
  tags?: string[];                      // Associated tags
}

/**
 * Base interface for diary notes (maintains compatibility with existing code)
 */
export interface DiaryNote {
  id: string;                           // Unique ID
  text: string;                         // Entry text
  time: string;                         // Hours:Minutes formatted string
  origin?: string;                      // Module of origin: "water" | "food" | "movement" | "sleep" | "measurements" | "digestion" | "purchases" | "habits" | "recipes" | "thoughts"
  isVoice?: boolean;                    // Voice dictation indicator
  isImportant?: boolean;                // Favorites system
  isPinned?: boolean;                   // Anchored to the top
  sealedUntilDay?: number;              // Time Capsule cycle day (e.g. 15 or 28), 0 or undefined for normal cards
}

/**
 * State for a single diary day
 */
export interface DiaryDayState {
  index: number;                        // Day index in the cycle
  notes: DiaryTimelineItem[];           // All notes for the day
  mood?: string;                        // Mood for the day
  bookmark?: string;                    // Bookmark/tag for the day
  photoUrl?: string;                    // Optional photo for the day (from existing assets)
}

/**
 * Categories available in the diary composer
 */
export type DiaryComposerCategory =
  | "thoughts"
  | "water"
  | "food"
  | "movement"
  | "sleep"
  | "measurements"
  | "digestion"
  | "purchases"
  | "habits"
  | "recipes";

/**
 * Thumbnail metadata for diary entries
 */
export interface DiaryThumbnail {
  url: string;                          // URL of the thumbnail
  alt?: string;                         // Alternative text
  type: "module-asset" | "recipe-image" | "icon"; // Type of thumbnail
}
